# Generated by Django 2.2 on 2020-10-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201013_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.IntegerField(blank=True, default=0, help_text='用户积分换算比例： 1RMB=10积分', null=True, verbose_name='用户积分'),
        ),
    ]
