# Generated by Django 2.2 on 2020-10-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='expire_text',
            field=models.CharField(default=None, max_length=150, verbose_name='有效周期[文本]'),
            preserve_default=False,
        ),
    ]
