# Generated by Django 2.2 on 2020-10-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail_expire_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
    ]
