"""
Django settings for luffyapi project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent  # 项目的主应用目录

# 新增一个系统导包路径，引入子应用
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret keys used in production secret!
SECRET_KEY = '(j%k$udj)5803#j8-ew3qsyb=y@y7g#x@58vu!(t_&r&s3_^h2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["api.bzboy.info"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',          # 跨域设置
    'xadmin',               # xadmin后台管理
    'crispy_forms',         # 表单美化组件
    'reversion',            #
    'rest_framework',       # 接口组件
    'django_filters',       # filter过滤需要加载的应用
    'ckeditor',             # 富文本编译器
    'ckeditor_uploader',    # 富文本编译器上传图片

    'home.apps.HomeConfig',                 # 主页面的应用
    'users.apps.UsersConfig',                # 用户应用
    'courses.apps.CourseConfig',              # 课程应用
    'cart.apps.CartConfig',                 # 购物车应用
    'orders.apps.OrdersConfig',               # 订单应用
    'coupon.apps.CouponConfig',               # 优惠券应用
    'payments.apps.PaymentsConfig',             # 支付功能
]

# 配置文件中注册users应用
AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# JWT配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    # 异常处理
    'EXCEPTION_HANDLER': 'luffyapi.utils.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'send_power': '20/day'
    }
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=3),
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'users.utils.jwt_response_payload_handler',
}

ROOT_URLCONF = 'luffyapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'luffyapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.mysql",
        "HOST": "127.0.0.1",
        "PORT": 3306,
        "USER": "luffy_user",
        "PASSWORD": "luffy",
        "NAME": "luffy",
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {  # 日志的处理格式
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            # 日志位置,日志文件名,日志保存目录必须手动创建
            'filename': os.path.join(os.path.dirname(BASE_DIR), "logs/renran.log"),
            # 单个日志文件的最大值,这里我们设置300M
            'maxBytes': 300 * 1024 * 1024,
            # 备份日志文件的数量,设置最大日志数量为10
            'backupCount': 10,
            # 日志格式:详细格式
            'formatter': 'verbose'
        },
    },
    # 日志对象
    'loggers': {
        'django': {  # 固定，将来django内部也会有异常的处理，只会调用django下标的日志对象
            'handlers': ['console', 'file'],
            'propagate': True,  # 是否让日志信息继续冒泡给其他的日志处理系统
        },
    }
}

# 引入自定义认证类
AUTHENTICATION_BACKENDS = ['users.utils.AuthModelBackend',]

# CORS组的配置信息
CORS_ORIGIN_WHITELIST = (
    'http://luffy.bzboy.info',
)
CORS_ALLOW_CREDENTIALS = True  # 不允许ajax跨域请求时携带cookie

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# 项目中存储上传文件的根目录【暂时设置】，upload目录需要手动配置
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")
# 访问上传文件的url地址前缀
MEDIA_URL = "/media/"

# 腾讯防水墙配置
TENCENT_CAPTCHA = {
    "GATEWAY": "https://ssl.captcha.qq.com/ticket/verify",
    "APPID": "2050295557",  # 此处的APPID一定要和客户端的APPID保持一致，否则后面票据会失败！
    "App_Secret_Key": "0xX9nA34W-MSsAy_Z1zmRTA**",
}

# Redis缓存数据库配置
CACHES = {
    "default": {   # 默认缓存
        "BACKEND": "django_redis.cache.RedisCache",
        # 项目上线需要调整路径
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "session": {   # xadmin或admin的session存储
        "BACKEND": "django_redis.cache.RedisCache",
        # 项目上线需要调整路径
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "sms_code": {   # 短信验证码存储
        "BACKEND": "django_redis.cache.RedisCache",
        # 项目上线需要调整路径
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "cart": {   # 购物车数据存储
        "BACKEND": "django_redis.cache.RedisCache",
        # 项目上线需要调整路径
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

# 阿里云参数
ACCESSKEY_ID = "LTAI4GA******gLJTNz"
ACCESSKEY_SERECT = "Xi6k**********0Eyz"
REGION_ID = "cn-beijing"
SIGN_NAME = "b***y"  # 签名
ROLE_ARN = "acs***********acer"
SMS_TEMPLATE_ID = {
    'login': 'SMS_****283',  # 登录使用的模板id
    'register': 'SMS_****376',  # 修注册使用的模板id
}

# 富文本编辑器ckeditor
CKEDITOR_CONFIGS = {
    'default': {
        # 'toolbar': "full",  # 工具条功能, full默认值，使用所有的工具栏显示给用户
        # 'height': 300,      # 编辑器高度
        # 'width'： 300,    # 编辑器宽度
        'toolbar': 'Basic',
        'toolbar_Basic': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter',
             'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ['Smiley', 'Table', "Image", 'Blockquote']
        ]
    },
}

CKEDITOR_UPLOAD_PATH = ''  # 上传文件保存路径，留空则保存django的文件上传路径

# 支付宝配置信息
ALIAPY = {
    #  "gateway_url": "https://openapi.alipay.com/gateway.do?",  # 真实支付宝网关地址
    "gateway_url": "https://openapi.alipaydev.com/gateway.do?",  # 沙箱支付宝网关地址
    "appid": "2021000119635206",  # 应用ID
    "app_private_key_path": os.path.join(BASE_DIR, "apps/payments/keys/app_private_key.pem"),
    "alipay_public_key_path": os.path.join(BASE_DIR, "apps/payments/keys/alipay_public_key.pem"),
    "sign_type": "RSA2",  # 秘钥加密类型
    "return_url": "http://www.luffycity.cn:8080/payments/alipay/result",  # 同步回调地址
    "notify_url": "http://api.luffycity.cn:8000/payments/alipay/result",  # 异步结果通知
}

# 保利威视频加密服务
POLYV_CONFIG = {
    "userId": "b94978510f",  # 用户ID/appid
    "secretkey": "8RKY40w5w5",  # 秘钥
    "tokenUrl": "https://hls.videocc.net/service/v1/token",
}

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')


