# Generated by Django 2.2 on 2020-10-13 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20201013_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 12, 57, 53, 442681, tzinfo=utc), verbose_name='优惠券的启用时间'),
        ),
    ]
