# Generated by Django 2.2 on 2020-10-16 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20201013_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 7, 55, 39, 921052, tzinfo=utc), verbose_name='优惠券的启用时间'),
        ),
    ]
