# Generated by Django 2.2 on 2020-10-13 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201013_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 12, 50, 58, 485747, tzinfo=utc), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 12, 50, 58, 485720, tzinfo=utc), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='activitydiscount',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='coursediscount',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='coursediscounttype',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='courseexpire',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
    ]
