# Generated by Django 2.2 on 2020-10-13 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201013_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 12, 57, 53, 438645, tzinfo=utc), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 12, 57, 53, 438618, tzinfo=utc), verbose_name='开始时间'),
        ),
    ]
